### ISSUE TITLE
Add support for the Shelly H&T

### ISSUE THREAD

**Issue by tim-hellhake** [tim-hellhake/shelly-adapter#13]

**Comment by tim-hellhake** [comment]
Works only with MQTT (#15 ).

**Comment by fpilo** [comment]
Hi,
is there any possibility to connect the Shelly H&T to webthings? Via MQTT?
Many thanks

**Comment by tim-hellhake** [comment]
The Shelly HT is now supported via HTTP.
Most of the time the sensor is in sleep mode.
To add it reconnect the power shortly before starting the search.

**Comment by fpilo** [comment]
Great! When will the new version available for testing?

**Comment by tim-hellhake** [comment]
Version `1.2.0` should be available now.

**Comment by fpilo** [comment]
It works, I'll report any issue in the next days, many thanks, very good work! Ciao
