### ISSUE TITLE
Shelly 2.5 not recognized as roller shutter anymore

### ISSUE THREAD

**Issue by rmeissn** [tim-hellhake/shelly-adapter#17]
My Shelly 2.5 received an official update (now at v1.8.3) and my roller shutter rules stopped working.
I'm not sure which version broke the current webthing rules, but I can't trigger the roller shutter anymore from within the webthings gateway UI. The Roller shutter is now recognized as a switch, with 2 relays, instead of a roller shutter.

**Comment by rmeissn** [comment]
I guess updating the dependency "shellies" to it's current version (v1.0.2) might solve this, as the commits state a lot about device identification.

**Comment by tim-hellhake** [comment]
I updated `shellies` to the latest version.
Can you please try the new release after the PR is merged?

**Comment by rmeissn** [comment]
The new release recognizes the device as a roller shutter again. Many thanks for the update!
