### ISSUE TITLE
Shelly 1PM power and other attributes not reported

### ISSUE THREAD

**Issue by panyamin** [tim-hellhake/shelly-adapter#18]
Hello,

I have some Shellies 1PM, and since last release power meter is not reported by the addon.

In fact, the `shellies` package since v1.0.0 has changed attributes of devices, for example, **before v1.0.0** :

```
Shelly1PM {
  _events: Events <[Object: null prototype] {}> {},
  _eventsCount: 0,
  type: 'SHSW-PM',
  id: 'xxxxx',
  _online: true,
  _ttl: 3840000,
  _ttlTimer: Timeout {
    _idleTimeout: 3840000,
    _idlePrev: [TimersList],
    _idleNext: [Timeout],
    _idleStart: 11148,
    _onTimeout: [Function],
    _timerArgs: undefined,
    _repeat: null,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(asyncId)]: 21,
    [Symbol(triggerId)]: 15
  },
  _name: null,
  _props: Map { '*' => Map { 111 => 'powerMeter0', 112 => 'relay0' } },
  _request: null,
  host: [Getter/Setter],
  settings: [Getter/Setter],
  powerMeter0: [Getter/Setter],
  relay0: [Getter/Setter]
}
```

**Since v1.0.0 :** 

```
Shelly1PM {
  _events: Events <[Object: null prototype] {}> {},
  _eventsCount: 0,
  id: 'xxxx',
  lastSeen: 2020-10-15T20:02:59.278Z,
  _online: true,
  _ttl: 3840000,
  _ttlTimer: Timeout {
    _idleTimeout: 3840000,
    _idlePrev: [TimersList],
    _idleNext: [TimersList],
    _idleStart: 12144,
    _onTimeout: [Function],
    _timerArgs: undefined,
    _repeat: null,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(asyncId)]: 18,
    [Symbol(triggerId)]: 15
  },
  _name: null,
  _props: Map {
    '*' => Map {
      112 => 'relay0',
      1101 => 'relay0',
      118 => 'input0',
      2101 => 'input0',
      2102 => 'inputEvent0',
      2103 => 'inputEventCounter0',
      119 => 'externalTemperature0',
      3101 => 'externalTemperature0',
      3201 => 'externalTemperature1',
      3301 => 'externalTemperature2',
      3103 => 'externalHumidity',
      3117 => 'externalInput0',
      111 => 'power0',
      4101 => 'power0',
      4103 => 'energyCounter0',
      6102 => 'overPower',
      6109 => 'overPowerValue',
      113 => 'deviceTemperature',
      3104 => 'deviceTemperature',
      115 => 'overTemperature',
      6101 => 'overTemperature'
    }
  },
  _request: null,
  host: [Getter/Setter],
  settings: [Getter/Setter],
  relay0: [Getter/Setter],
  input0: [Getter/Setter],
  inputEvent0: [Getter/Setter],
  inputEventCounter0: [Getter/Setter],
  externalTemperature0: [Getter/Setter],
  externalTemperature1: [Getter/Setter],
  externalTemperature2: [Getter/Setter],
  externalHumidity: [Getter/Setter],
  externalInput0: [Getter/Setter],
  power0: [Getter/Setter],
  energyCounter0: [Getter/Setter],
  overPower: [Getter/Setter],
  overPowerValue: [Getter/Setter],
  deviceTemperature: [Getter/Setter],
  overTemperature: [Getter/Setter]
}
```

As you can see `powerMeter0` is now `power0`.

There is also `deviceTemperature` instead of `internalTemperature` [used here in addon](https://github.com/tim-hellhake/shelly-adapter/blob/781f97186911599ca80bd214512034f4e69af952/src/shelly-device.ts#L56), and a lot of new properties that can maybe usefull to report if available.

I guess, this output is the same for all Shellies types..

I can prepare a PR if you want?

**Comment by tim-hellhake** [comment]
> I can prepare a PR if you want?

Sure, feel free :)

**Comment by panyamin** [comment]
> 
> 
> > I can prepare a PR if you want?
> 
> Sure, feel free :)

Okay, I'll try to do something this weekend.

Do you have any other type of Shellies? I would like to know if the output is the same for all the types. I used the example of the `shellies` package: https://github.com/alexryd/node-shellies#basic-usage-example

**Comment by tim-hellhake** [comment]
> Do you have any other type of Shellies?

I have a shelly 2.5 and a shelly dimmer.

Did you already start to work on this?
I just received another report that the shellies are not online due to multicast problems.
I'm thinking about replacing the library and using the shellies REST API directly.
Their REST API seems to pretty stable.

**Comment by panyamin** [comment]
> I have a shelly 2.5 and a shelly dimmer.

Could you test the new output with the example?

> Did you already start to work on this?

Yes, I'm currently testing the [changes](https://github.com/panyamin/shelly-adapter/commits/feature/update-properties) in my setup

> I just received another report that the shellies are not online due to multicast problems.
> I'm thinking about replacing the library and using the shellies REST API directly.
> Their REST API seems to pretty stable.

Isn't going to be less real-time? I mean, status of the relay, or the power meter will not be pushed anymore, unless the REST API has a pub/sub mechanism?

**Comment by tim-hellhake** [comment]
> Could you test the new output with the example?

Sure

> Yes, I'm currently testing the changes in my setup

Just create a draft PR, I can test your changes locally.

> Isn't going to be less real-time? I mean, status of the relay, or the power meter will not be pushed anymore, unless the REST API has a pub/sub mechanism?

Yeah, that's why I hesitated to that.

**Comment by panyamin** [comment]
> Just create a draft PR, I can test your changes locally.

Sure, draft PR created : https://github.com/tim-hellhake/shelly-adapter/pull/19

**Comment by tim-hellhake** [comment]
I updated my Shelly 2.5 to the latest firmware revision:

```
Shelly25 {
  _events: {},
  _eventsCount: 0,
  id: 'ECFAC214A1BA',
  lastSeen: 2020-10-19T20:49:02.917Z,
  _online: true,
  _ttl: 3840000,
  _ttlTimer:
   Timeout {
     _called: false,
     _idleTimeout: 3840000,
     _idlePrev: [TimersList],
     _idleNext: [TimersList],
     _idleStart: 491,
     _onTimeout: [Function],
     _timerArgs: undefined,
     _repeat: null,
     _destroyed: false,
     [Symbol(unrefed)]: false,
     [Symbol(asyncId)]: 47,
     [Symbol(triggerId)]: 30 },
  _name: null,
  _props:
   Map {
     '*' => Map {
       112 => 'relay0',
       1101 => 'relay0',
       122 => 'relay1',
       1201 => 'relay1',
       118 => 'input0',
       2101 => 'input0',
       2102 => 'inputEvent0',
       2103 => 'inputEventCounter0',
       128 => 'input1',
       2201 => 'input1',
       2202 => 'inputEvent1',
       2203 => 'inputEventCounter1',
       111 => 'power0',
       4101 => 'power0',
       4102 => 'power0',
       4103 => 'energyCounter0',
       4104 => 'energyCounter0',
       9101 => 'mode',
       115 => 'deviceTemperature',
       3104 => 'deviceTemperature',
       117 => 'overTemperature',
       6101 => 'overTemperature' },
     'relay' => Map {
       6102 => 'overPower0',
       6202 => 'overPower1',
       6109 => 'overPowerValue',
       121 => 'power1',
       4201 => 'power1',
       4203 => 'energyCounter1' },
     'roller' => Map {
       1102 => 'rollerState',
       113 => 'rollerPosition',
       1103 => 'rollerPosition',
       6103 => 'rollerStopReason' } },
  _request: null,
  host: [Getter/Setter],
  settings: [Getter/Setter],
  relay0: [Getter/Setter],
  relay1: [Getter/Setter],
  input0: [Getter/Setter],
  inputEvent0: [Getter/Setter],
  inputEventCounter0: [Getter/Setter],
  input1: [Getter/Setter],
  inputEvent1: [Getter/Setter],
  inputEventCounter1: [Getter/Setter],
  power0: [Getter/Setter],
  energyCounter0: [Getter/Setter],
  mode: [Getter/Setter],
  overPower0: [Getter/Setter],
  overPower1: [Getter/Setter],
  overPowerValue: [Getter/Setter],
  rollerState: [Getter/Setter],
  rollerPosition: [Getter/Setter],
  rollerStopReason: [Getter/Setter],
  power1: [Getter/Setter],
  energyCounter1: [Getter/Setter],
  deviceTemperature: [Getter/Setter],
  overTemperature: [Getter/Setter] }
```

**Comment by panyamin** [comment]
Okay, so it seems they changed the properties for all shellies.

So, notable changes for the current implementation in the addon:

- `internalTemperature` seems is now `deviceTemperature` 
- `powerMeterN` is now `powerN`

**Comment by tim-hellhake** [comment]
> internalTemperature seems is now deviceTemperature

I already mentioned that in the PR :grimacing:
If you remove the obsolete `internalTemperature` i can merge the PR.

**Comment by tim-hellhake** [comment]
> internalTemperature seems is now deviceTemperature

I also mentioned that in the PR grimacing
If you remove the obsolete `internalTemperature` i can merge the PR.

**Comment by tim-hellhake** [comment]
> internalTemperature seems is now deviceTemperature

I also mentioned that in the PR grimacing :grimacing: 
If you remove the obsolete `internalTemperature` i can merge the PR.

**Comment by tim-hellhake** [comment]
I just built and tested it locally with my shellies.
Everything looks good so far :tada: 
Just one thing: currently the update will break existing rules as the property names changed.
I think I need to add a little translation layer to avoid that.

**Comment by panyamin** [comment]
Nice! 🎊

Oh, yes, this will be surely a "breaking changes" release as is..!

Maybe a simple aliases class?

**Comment by tim-hellhake** [comment]
I added a second property map with the shelly property names as keys.
That should do the trick.
I'll do some testing now.
If everything works fine, I will create a new Update, which should available soon.
Thanks for the help and feedback!

**Comment by panyamin** [comment]
Okay, nice!



> Thanks for the help and feedback!

No problem, my pleasure 😉

**Comment by tim-hellhake** [comment]
As soon as the PR is merged you should be able to see the new update :raised_hands:

**Comment by panyamin** [comment]
Awesome! 👏

**Comment by tim-hellhake** [comment]
Is everything working? :smile:

**Comment by panyamin** [comment]
Yes! Working great! 😁

**Comment by tim-hellhake** [comment]
> Yes! Working great!

If you have any further ideas just open a new issue
