### ISSUE TITLE
Dimmer not visible

### ISSUE THREAD

**Issue by fpilo** [tim-hellhake/shelly-adapter#2]
I cannot connect the new shelly dimmer. Is it possible to add thai improvement? Thanks

**Comment by tim-hellhake** [comment]
@fpilo
I'll add it but I need your help to test it.

**Comment by fpilo** [comment]
Ok, no problem




Ottieni Outlook per Android







On Thu, Dec 19, 2019 at 9:49 PM +0100, "Tim Hellhake" <notifications@github.com> wrote:












@fpilo

I'll add it but I need your help to test it.

**Comment by tim-hellhake** [comment]
@fpilo
A new version is available.
Could you please test if the dimmer is now visible?

**Comment by fpilo** [comment]
Ok, the dimmer is now visible. No way to turn it on/off or change the brightness. Is it normal?

**Comment by tim-hellhake** [comment]
> No way to turn it on/off or change the brightness

Are there no properties, or do the properties have no effect?

**Comment by fpilo** [comment]
The properties are shown but they have no effect. Moreover the brigthness is presented as a switch  and not a slider. 




Ottieni Outlook per Android







On Sat, Dec 21, 2019 at 8:24 PM +0100, "Tim Hellhake" <notifications@github.com> wrote:













No way to turn it on/off or change the brightness



Are there no properties, or do the properties have no effect?

**Comment by tim-hellhake** [comment]
> Moreover the brigthness is presented as a switch  and not a slider

That's the easy part.

> The properties are shown but they have no effect

Could you please attach the logs for this one?

**Comment by tim-hellhake** [comment]
The `brightness` property should be a slider with the next release.
You may have to hard reload (ctrl + shift + r) the things page to see the slider.

**Comment by fpilo** [comment]
Ok, now the dimmer is visible and correctly working.

I’ll continue testing and eventually refer to you for minor bugs. 

Many thanks,

 

Happy Christmas!

Ciao,

Federico

 

Da: Tim Hellhake <notifications@github.com> 
Inviato: domenica 22 dicembre 2019 00:51
A: tim-hellhake/shelly-adapter <shelly-adapter@noreply.github.com>
Cc: Federico Pilo <federico.pilo@pi.infn.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [tim-hellhake/shelly-adapter] Dimmer not visible (#2)

 

The brightness property should be a slider with the next release.
You may have to hard reload (ctrl + shift + r) the things page to see the slider.

**Comment by tim-hellhake** [comment]
> Ok, now the dimmer is visible and correctly working.

Wonderful!

> I’ll continue testing and eventually refer to you for minor bugs.

Feel free to create new issues if you have any problems.

Merry Christmas Federico!
