### ISSUE TITLE
Shelly 2.5 not discovered

### ISSUE THREAD

**Issue by roman-1983** [tim-hellhake/shelly-adapter#21]
Hi @tim-hellhake , hi team!

Thanks for you work. Unfortunately my Webthings Gateway is not discovering a Shelly 2.5 i just installed.
It's correctly set up in my wifi, the app and its own web interface is working (local and over the internet).

For test purpose i enabled cloud access and set up username + password of my shelly account in the webthings gateway

Could you please give me some hints how to debug the discover process to check whats wrong?

Device: Shelly 2.5
Firmware:  20200827-065456/v1.8.3@4a8bc427 (latest version since 24.11.2020)

**Comment by roman-1983** [comment]
That's the current log output:

2020-11-24 09:03:27.152 INFO   : shelly-adapter: Adapter: ShellyAdapter id ShellyAdapter pairing started
2020-11-24 09:03:27.154 INFO   : scheduler-adapter: Adapter: SchedulerAdapter id SchedulerAdapter pairing started
2020-11-24 09:03:27.352 INFO   : Opened a new things socket
2020-11-24 09:03:40.016 INFO   : thing-url-adapter: Adapter: ThingURLAdapter id thing-url-adapter pairing cancelled
2020-11-24 09:03:40.018 INFO   : shelly-adapter: Adapter: ShellyAdapter id ShellyAdapter pairing cancelled

**Comment by tim-hellhake** [comment]
Hi @roman-1983 :)

> Unfortunately my Webthings Gateway is not discovering a Shelly 2.5 i just installed

I'm sorry to hear that.

> That's the current log output

According to the log, no shelly device was discovered.

> Could you please give me some hints how to debug the discover process to check whats wrong?

Sure!
The adapter uses the `node-shellies` library, which relies on COAP and multicast communication to discover devices and receive updates.
The library starts a COAP server on the multicast address `224.0.1.187`.
To receive multicast traffic, your nic must join a multicast group.
You can check the joined groups `sudo netstat -g`.

```
IPv6/IPv4 Group Memberships
Interface       RefCnt Group
--------------- ------ ---------------------
lo              1      224.0.1.187
...
eth0            1      224.0.1.187
```

If that's the case, you should receive multicast traffic from your shelly devices.
You can dump the traffic using `sudo tcpdump udp port 5683`.
If you want to force the shelly to send some packets, just toggle one of the relays.

Some network devices only relay multicast traffic you subscribed to.
To inform them your system sends IGMP membership reports.
You can dump them with `sudo tcpdump -e igmp -vv`.
There should be at least one report after starting/stopping the adapter.

**Comment by tim-hellhake** [comment]
@roman-1983 Did you have any success?

**Comment by tim-hellhake** [comment]
I'm closing this now.
If you still have problems please let me know.

**Comment by roman-1983** [comment]
Sorry for not replying. Totally forgot this issue...
I am not having any issues anymore.

Thank you for your engagement! :-)
