### ISSUE TITLE
Unable to control ShellyPlugS (Error: addMembership EADDRINUSE)

### ISSUE THREAD

**Issue by seteahconnoc** [tim-hellhake/shelly-adapter#31]
Hello. Thank you for your work. I am able to use my ShellyPlugS via the ShellyCloudApp. I successfully added the device using my WebThings Gateway. Sadly, I cannot control the plug. Using the switch named "Relay" shows no effect. Any help would be appreciated. Feel free to ask for further details (e. g. log entries). I guess that it could relate to this error message:
`2021-10-21 18:51:15.965 ERROR  : shelly-adapter: Error: addMembership EADDRINUSE`

**Comment by tim-hellhake** [comment]
I saw this error before (#22).
Please try to set the multicast interface in the settings.
The ethernet interface is usually called `eth0` and the wifi interface `wlan0`.

**Comment by seteahconnoc** [comment]
@tim-hellhake Thank your very much. Now, it worked like a charm.
Actually, I read the issue, you mentioned, but didn't figure out that my problem could be solved the same way.

I am quite happy for being able to use a smart plug now. In fact, I used MerossSmartPlugs, until something changed and I couldn't figure out the problem. Afterwards, I unsuccessfully tried out "TP-Link Tapo"-SmartPlugs.

**Comment by tim-hellhake** [comment]
Glad I could help :)
