### ISSUE TITLE
Shelly 1 v3 not recognized

### ISSUE THREAD

**Issue by Fodox76** [tim-hellhake/shelly-adapter#4]
Hello,
I have a Shelly 1 v.3 relay (firmware version 20191216-090109/v1.5.7@c30657ba) already working with his own app and with google mini.
I want to add it to my mozilla.iot too, version 0.10.0 running on docker with raspbian and Raspberry. The Shelly add-on is version 0.2.1. When I launch new things search, my shelly 1 is not recognized. I see nothing important in the log:

> 2020-01-12 11:00:22.803 INFO   : About to call startPairing on ZigbeeAdapter
> 2020-01-12 11:00:22.807 INFO   : About to call startPairing on VirtualThingsAdapter
> 2020-01-12 11:00:22.811 INFO   : About to call startPairing on ShellyAdapter
> 2020-01-12 11:00:22.834 INFO   : Opened a new things socket
> 2020-01-12 11:00:22.872 INFO   : zigbee: Pairing mode started, timeout = 60
> 2020-01-12 11:00:22.876 INFO   : shelly: Adapter: ShellyAdapter id ShellyAdapter pairing started
> 2020-01-12 11:01:22.824 INFO   : Pairing timeout
> 2020-01-12 11:01:22.829 ERROR  : Thing was not added
> 2020-01-12 11:01:22.832 ERROR  : addNewThing cancelled
> 2020-01-12 11:01:22.840 INFO   : virtual-things: Adapter: VirtualThingsAdapter id virtual-things pairing cancelled
> 2020-01-12 11:01:22.844 INFO   : zigbee: Cancelling pairing mode
> 2020-01-12 11:01:22.848 INFO   : shelly: Adapter: ShellyAdapter id ShellyAdapter pairing cancelled

Shelly 1 is connected to my ADSL wi-fi router using 2.4Ghz channel and dynamic IP. Raspberry PI is connected by LAN with static IP. Inside Raspbian and Mozilla.IOT into Docker, I can ping Shelly IP: so it is visible.
Is there something wrong in my configuration?
Can you help me?

Thanks
Fod.

**Comment by tim-hellhake** [comment]
Sorry for the late reply.
I wasn't aware of this issue.

> version 0.10.0 running on docker

The adapter uses multicast messages to discover shelly devices.
It's possible that the Docker network breaks the multicast communication.
How did you start the Docker container?

**Comment by Fodox76** [comment]
Hello, not a problem, nice to ear you ^_^
I start docker container with this command:
`docker run -d -v /var/docker/mozillaiot:/home/node/.mozilla-iot --net=host --device=/dev/ttyACM0 --name mozillaiot mozillaiot/gateway:arm` 
I have a zigbee dongle too, the Conbee2.
Today I tried to use WireShark to try analyze outgoing requests, but I had problem with acces privileges to eth0.

**Comment by tim-hellhake** [comment]
> Hello, not a problem, nice to ear you ^_^

I'm glad to hear that.

Strange, I would expect it to work with `--net=host`.
I'll try to reproduce it on my pi.

**Comment by tim-hellhake** [comment]
Sorry for the delay.
I checked it with the latest gateway docker image and my shelly was discovered right away.
Any chance that you have avahi also running on your host system?

**Comment by Fodox76** [comment]
Hi Tim, I haven't avahi but I can install it if needed: tell me a bit more.
In addiction, maybe you could send me a version of your add-on with more log in the code, to better understand what's appen.
This is the json configuration of my Shelly1 obtained by "http://192.168.1.139/settings", you can compare it with your Shelly to find differences:

> {
  "device": {
    "type": "SHSW-1",
    "mac": "98F4ABF4307F",
    "hostname": "shelly1-F4307F",
    "num_outputs": 1
  },
  "wifi_ap": {
    "enabled": false,
    "ssid": "shelly1-F4307F",
    "key": ""
  },
  "wifi_sta": {
    "enabled": true,
    "ssid": "SsidOfMyWiFiConnection_2.4",
    "ipv4_method": "dhcp",
    "ip": null,
    "gw": null,
    "mask": null,
    "dns": null
  },
  "wifi_sta1": {
    "enabled": false,
    "ssid": null,
    "ipv4_method": "dhcp",
    "ip": null,
    "gw": null,
    "mask": null,
    "dns": null
  },
  "mqtt": {
    "enable": false,
    "server": "192.168.33.3:1883",
    "user": "",
    "id": "shelly1-F4307F",
    "reconnect_timeout_max": 60,
    "reconnect_timeout_min": 2,
    "clean_session": true,
    "keep_alive": 60,
    "max_qos": 0,
    "retain": false,
    "update_period": 30
  },
  "sntp": {
    "server": "time.google.com",
    "enabled": true
  },
  "login": {
    "enabled": false,
    "unprotected": false,
    "username": "admin",
    "password": "admin"
  },
  "pin_code": "$*iyP(",
  "name": "",
  "fw": "20200206-083100/v1.5.10@e6a4205e",
  "build_info": {
    "build_id": "20200206-083100/v1.5.10@e6a4205e",
    "build_timestamp": "2020-02-06T08:31:00Z",
    "build_version": "1.0"
  },
  "cloud": {
    "enabled": true,
    "connected": true
  },
  "timezone": "Europe/Rome",
  "lat": 45.4655,
  "lng": 9.18652,
  "tzautodetect": true,
  "tz_utc_offset": 3600,
  "tz_dst": false,
  "tz_dst_auto": true,
  "time": "23:43",
  "hwinfo": {
    "hw_revision": "prod-2019-08",
    "batch_id": 0
  },
  "mode": "relay",
  "relays": [
    {
      "name": null,
      "ison": false,
      "has_timer": false,
      "default_state": "last",
      "btn_type": "toggle",
      "btn_reverse": 0,
      "auto_on": 0,
      "auto_off": 0,
      "power": 0,
      "btn_on_url": null,
      "btn_off_url": null,
      "out_on_url": null,
      "out_off_url": null,
      "longpush_url": null,
      "shortpush_url": null,
      "schedule": false,
      "schedule_rules": []
    }
  ]
}

thank you
Fod.

**Comment by tim-hellhake** [comment]
I just tried it with a fresh untouched system using the following steps:

* Flash `2020-02-13-raspbian-buster-lite.zip` to a fresh SD card.
* Install docker from https://get.docker.com
* Run the docker image as explained [here](https://github.com/mozilla-iot/gateway-docker).
```
docker run \
    -d \
    -e TZ=America/Los_Angeles \
    -v /path/to/shared/data:/home/node/.mozilla-iot \
    --network="host" \
    --log-opt max-size=1m \
    --log-opt max-file=10 \
    --name webthings-gateway \
    mozillaiot/gateway:arm
```
* Install the shelly adapter (current version 0.4.1)
* Open the _add things_ dialog
* Add the new device

Just to be sure I also reseted my shelly to factory settings.
My firmware version is `20191216-090135/v1.5.7@c30657ba`.
Everything seems to work.
I'm not sure why the discovery is not working for you.
Maybe something in your network is messing with the discovery.

**Comment by tim-hellhake** [comment]
I just tried it with a fresh untouched system using the following steps:

Flash 2020-02-13-raspbian-buster-lite.zip to a fresh SD card.
Install docker from https://get.docker.com
Run the docker image as explained here.
docker run \
    -d \
    -e TZ=America/Los_Angeles \
    -v /path/to/shared/data:/home/node/.mozilla-iot \
    --network="host" \
    --log-opt max-size=1m \
    --log-opt max-file=10 \
    --name webthings-gateway \
    mozillaiot/gateway:arm
Install the shelly adapter (current version 0.4.1)
Open the add things dialog
Add the new device
Just to be sure I also reseted my shelly to factory settings.
Everything seems to work.
I'm not sure why the discovery is not working for you.
Maybe something in your network is messing with the discovery.

**Comment by tim-hellhake** [comment]
I just tried it with a fresh untouched system using the following steps:

* Flash `2020-02-13-raspbian-buster-lite.zip` to a fresh SD card.
* Install docker from https://get.docker.com
* Run the docker image as explained [here](https://github.com/mozilla-iot/gateway-docker).
```
docker run \
    -d \
    -e TZ=America/Los_Angeles \
    -v /path/to/shared/data:/home/node/.mozilla-iot \
    --network="host" \
    --log-opt max-size=1m \
    --log-opt max-file=10 \
    --name webthings-gateway \
    mozillaiot/gateway:arm
```
* Install the shelly adapter (current version 0.4.1)
* Open the _add things_ dialog
* Add the new device

Just to be sure I also reseted my shelly to factory settings.
Everything seems to work.
I'm not sure why the discovery is not working for you.
Maybe something in your network is messing with the discovery.

**Comment by tim-hellhake** [comment]
> In addiction, maybe you could send me a version of your add-on with more log in the code, to better understand what's appen.

The discovery is located in the `shellies` library.
There is not much I could log.

**Comment by Fodox76** [comment]
I will try to remove docker container and then installl again, then I will try to install Wireshark into my Raspbian host.
Last question before that: the file you linked **node-shellies/lib/coap/index.js**  contain the multicast address 224.0.1.187. If I type:

` sudo netstat -g`

into Raspbian, it show:
```
pi@RPI-SERVER:~ $ sudo netstat -g
IPv6/IPv4 Group Memberships
Interface       RefCnt Group
--------------- ------ ---------------------
lo              1      224.0.1.187
lo              1      224.0.0.251
lo              1      all-systems.mcast.net
eth0            1      224.0.1.187
eth0            3      224.0.0.251
eth0            5      239.255.255.250
eth0            1      all-systems.mcast.net
docker0         1      239.255.255.250
docker0         2      224.0.0.251
docker0         1      all-systems.mcast.net
lo              1      ip6-allnodes
lo              1      ff01::1
eth0            2      ff02::fb
eth0            1      ff02::1:ff81:e3a6
eth0            1      ip6-allnodes
eth0            1      ff01::1
docker0         1      ip6-allnodes
docker0         1      ff01::1
```
eth0 show the multicast IP 224.0.1.187, docker0 not... your have the same output?

**Comment by nakinigit** [comment]
I recently moved from raspi to linux mint 19.1 and installed Webthings Gateway via .deb. Shelly devices that had previously worked on the pi do not show up. Tasmota & TP-Link Kasa work fine, although I had to add each manually by entering IP's. There is no such option for Shelly.

**Comment by tim-hellhake** [comment]
> eth0 show the multicast IP 224.0.1.187, docker0 not... your have the same output?

On my pi, it shows the multicast IP on eth0 as well as on docker0.
I'm using a stock raspbian image with the latest docker version.

**Comment by tim-hellhake** [comment]
> Shelly devices that had previously worked on the pi do not show up

What do you see if you run `sudo netstat -g`?
Are your NICs members of the multicast group `224.0.1.187`?

> I had to add each manually by entering IP's. There is no such option for Shelly.

I'll try to find out if that's possible for shelly too.
Other than that there's not much I can do.
You could try to open an issue in the shellies [repo](https://github.com/alexryd/node-shellies) though.

**Comment by nakinigit** [comment]
Not sure what to be looking for:
```sudo netstat -g     
IPv6/IPv4 Group Memberships
Interface       RefCnt Group
--------------- ------ ---------------------
lo              1      224.0.1.187
lo              1      239.255.255.250
lo              1      224.0.0.251
lo              1      all-systems.mcast.net
enp0s25         1      224.0.1.187
enp0s25         1      233.89.188.1
enp0s25         1      239.255.255.250
enp0s25         1      224.0.0.251
enp0s25         1      all-systems.mcast.net
lo              1      ff02::fb
lo              1      ip6-allnodes
lo              1      ff01::1
enp0s25         1      ff02::fb
enp0s25         1      ff02::1:ffab:49bc
enp0s25         1      ip6-allnodes
enp0s25         1      ff01::1
```

**Comment by nakinigit** [comment]
More info from logs:
```cat run-app.log.2020-05-04 |grep shelly
2020-05-04 18:50:31.765 INFO   : Loading add-on: shelly-adapter
2020-05-04 18:50:32.389 INFO   : shelly-adapter: Failed to import platform utilities for linux-unknown. Network and system configuration features will be disabled.
2020-05-04 18:50:32.707 INFO   : shelly-adapter: Opening database: /etc/webthings-gateway/config/db.sqlite3
2020-05-04 18:50:33.084 INFO   : shelly-adapter: Loading add-on shelly-adapter from /etc/webthings-gateway/addons/shelly-adapter
2020-05-04 18:50:34.629 INFO   : tasmota-adapter: Discovered http service at shelly1-B8F028.local []
2020-05-04 18:50:36.633 INFO   : tasmota-adapter: shelly1-B8F028.local seems not to be a Tasmota device []
2020-05-04 18:50:37.553 INFO   : tasmota-adapter: Discovered http service at shelly1-C4F4AA.local []
2020-05-04 18:50:39.661 INFO   : tasmota-adapter: shelly1-C4F4AA.local seems not to be a Tasmota device []```

**Comment by tim-hellhake** [comment]
> Not sure what to be looking for:

> enp0s25         1      224.0.1.187`

It seems like the nic is listening to the correct multicast address.
Theoretically, the discovery should work.
You could try to open an issue in the [shellies](https://github.com/alexryd/node-shellies#readme) repo.
Maybe the author of the library has another idea of how to fix the discovery on your system.
